### ISSUE TITLE
Python: BonminModel not solving using Pool

### ISSUE THREAD

**Issue by tarun018** [stanle/madopt#20]
I am running the following program:
```python
import madopt
def sol(args):
   print args
   model, variables = args
   model.setObj(-1*(3*variables[0] + 4*variables[1]))
   model.solve()
   return

import multiprocessing

#Main Thread
model = madopt.BonminModel()
variables = []
variables.append(model.addIVar(name="x"))
variables.append(model.addIVar(name="y"))

model.addConstr(variables[0]+2*variables[1], ub=14)
model.addConstr(3*variables[0]-variables[1], lb=0)
model.addConstr(variables[0]-variables[1], ub=2)
```
Running using:
```python
sol((model, variables))
print model.has_solution #-->gives True
if model.has_solution:
   print -1*(3*variables[0].x + 4*variables[1].x) #-->gives -34
   print variables[0].x #-->gives 6.0
   print variables[1].x #-->gives 4.0
```
prints:
```bash
(<madopt.BonminModel object at 0x7f84371e5078>, [<madopt.Var object at 0x7f8437156e10>, <madopt.Var object at 0x7f843715f810>])
True
-34.0
6.0
4.0
```

While running using:
```python
a = multiprocessing.Pool(2)
p = a.apply_async(sol, args=((model,variables),))
sol = p.get()
print model.has_solution #--> gives False
if model.has_solution:
   print -1*(3*variables[0].x + 4*variables[1].x)
   print variables[0].x
   print variables[1].x
```
prints:
```bash
(<madopt.BonminModel object at 0x7f84371e5078>, [<madopt.Var object at 0x7f8437156e10>, <madopt.Var object at 0x7f843715f810>])
False
```

My use case is to declare n Bonmin models, their constraints and variables in the main thread as shown above (for 1 model) and then for multiple iterations of each model, update the objective function and solve it in n different processes in parallel, but I am unable to do so. Creating and setting model each time will take a lot of time and will be useless since only objective needs to be changed.

Any help will be deeply appreciated. Thanks in advance.

Also, Is there any support for Bonmin APIs in Java ?

**Comment by stanle** [comment]
I do not know any Java API.

is it possible that you can create the model within the thread?

I have played around with your second code, but it keeps crashing for me. So it will take some time to investigate.

**Comment by tarun018** [comment]
I am using madopt for my research code to be published soon. 

My use cases forces for me to create a model, declare its variables and constraints once in main thread, and only change objective within successive iterations. Since I need to change objective, I'll need access to variables within the thread.

Creating and declaring model again and again will take a lot of time in each iteration and will not be useful.

**Comment by paul-scott** [comment]
My understanding of the multiprocessing library is that it works by creating separate processes not threads (I think this is due to a fundamental problem with parallelisation in python).  The code is pickled (or something like that) as it is sent off to a worker.  Madopt models were not designed to be able to be trivially copied around in memory like that (in fact I think the copy constructors have been disabled in the underlying c++?).

I tried to run the above and got an "invalid pointer" error.  I suspect all the heap allocated memory is not being reconstructed correctly in the new process, and it is probably just trying to point back to the memory in the original process (which is not shared and cannot be accessed).

There is probably some way of making the models copy over correctly, but it is probably more work than anyone would want to commit to right now.

I know this is a pretty old issue so you have likely moved on by now or worked around it, but a working approach that I think would achieve what you want is to:
- spawn a bunch of workers (that remain alive)
- send them a message to construct their own local model (send them the model data required to do this)
- send them the jobs they need to perform (with the data required to indicate how they should change their objectives
- retrieve the results
- iterate on the last two

I don't know if there is a good way to do this with the multiprocessing library, so if it is no good you could look towards using something like redis to set up and communicate some basic message queues, or just do it over http with a library like tornado (passing json or something).
